### ISSUE TITLE
java.lang.ClassCastException: redstone.xmlrpc.XmlRpcStruct cannot be cast to redstone.xmlrpc.XmlRpcArray

### ISSUE THREAD

**Issue by tomparisi** [canbican/wordpress-java#53]
Hello, 
  I get this error during a call to Wordpress.getPost(). it is reproducible also calling the command line client
java -jar /tmp/jwordpress-0.6.3-cli.jar --user XXX --pass XXX --url XXX -os 116704
Exception in thread "main" java.lang.ClassCastException: redstone.xmlrpc.XmlRpcStruct cannot be cast to redstone.xmlrpc.XmlRpcArray
    at net.bican.wordpress.XmlRpcMapped.fromXmlRpcStruct(XmlRpcMapped.java:116)
    at net.bican.wordpress.Wordpress.getPost(Wordpress.java:1169)
    at net.bican.wordpress.Main.main(Main.java:144)

The exception is thrown at this line in XmlRpcMapped.java
XmlRpcArray vList = (XmlRpcArray) v;

The debugger says that when the exception is thrown v is a XmlRpcStruct and its value is the following
{parent=116754, metadata={file=/home/wpcom/public_html/wp-content/blogs.dir/bf3/91323380/files/2015/09/zzzleepandgo-1200.jpg, sizes=[], image_meta={aperture=0, copyright=, orientation=0, focal_length=0, iso=0, caption=, created_timestamp=0, credit=, camera=, title=, shutter_speed=0}, width=1217, height=694}, thumbnail=https://xxx.files.wordpress.com/2015/09/zzzleepandgo-1200.jpg?w=150, attachment_id=116755, link=https://siviaggia.files.wordpress.com/2015/09/zzzleepandgo-1200.jpg, caption=, description=, date_created_gmt=Fri Sep 25 10:02:58 CEST 2015, title=zzzleepandgo-1200}

(the value of the key "k" is "post_thumbnail"

Please tell me if I can help providing other information

Thanks.

**Comment by canbican** [comment]
I'm looking into that. Meanwhile, for the record, which version of Java are you using?

**Comment by tomparisi** [comment]
I have tried with java 7 and java 8

**Comment by bodiam** [comment]
Hi, same issue here:

```
java.lang.ClassCastException: redstone.xmlrpc.XmlRpcStruct cannot be cast to redstone.xmlrpc.XmlRpcArray
    at net.bican.wordpress.XmlRpcMapped.fromXmlRpcStruct(XmlRpcMapped.java:116)
    at net.bican.wordpress.Wordpress.fillFromXmlRpcArray(Wordpress.java:85)
    at net.bican.wordpress.Wordpress.getPosts(Wordpress.java:1208)
    at net.bican.wordpress.Wordpress$getPosts.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at wordpress.WordpressPublisher.publish(WordpressPublisher.groovy:24)
    at wordpress.WordpressPublisher$publish.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at wordpress.WordpressPublisherTest.testPublish(WordpressPublisherTest.groovy:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

If I can help in any way, please let me know. I can also create a test account for my site if you want.

I've just used your example code to publish an dummy test to Wordpress.

**Comment by canbican** [comment]
I will deploy the changes later on in the day. Please stay tuned :)

**Comment by bodiam** [comment]
W00t! Will test immediately when you have released a new version. Thanks for your quick response!

**Comment by canbican** [comment]
Quick explanation: This happens because it's a media item, not really a post. But if you ask for every post, they come in the package. In my opinion, wordpress guys applied neat technique they invented and I name it as **unexpected polymorphism**.

Since the idea behind getPosts is to *get posts*, I'm going to fix it by ignoring such entries. Does it look good?

**Comment by canbican** [comment]
It's a bit confusing that if post_thumbnail does not exist, it returns **[]**, otherwise **{...}**. I am confident this behavior will change and this will fail again. But anyway, I am uploading a new release, please check and let me know if it fixes things.

**Comment by tomparisi** [comment]
Hello.
It seems to work fine now. Thank you very much.
