### ISSUE TITLE
redstone.xmlrpc.XmlRpcException: The response could not be parsed

### ISSUE THREAD

**Issue by AchrafAmil** [canbican/wordpress-java#58]
The code : 
Wordpress wp = new Wordpress(username, password, xmlRpcUrl);
            FilterPost filter = new FilterPost() ;
            filter.setNumber(10);
            List<Post> posts = wp.getPosts(filter);

generates : 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
 SLF4J: Defaulting to no-operation (NOP) logger implementation
 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
redstone.xmlrpc.XmlRpcException: The response could not be parsed.
    at redstone.xmlrpc.XmlRpcClient.handleResponse(Unknown Source)
    at redstone.xmlrpc.XmlRpcClient.endCall(Unknown Source)
     at redstone.xmlrpc.XmlRpcClient.invoke(Unknown Source)
   at redstone.xmlrpc.XmlRpcProxy.invoke(Unknown Source)
   at java.lang.reflect.Proxy.invoke(Proxy.java:393)
   at net.bican.wordpress.$Proxy1.getPosts(Unknown Source)
 at net.bican.wordpress.Wordpress.getPosts(Wordpress.java:822)

:(

**Comment by ghost** [comment]
Can you add an SLF4J-compatible logging framework and set the logging level to ALL and paste your output?

**Comment by dolt131943** [comment]
Maybe response have include a blank line at top.I have this issue, and edit the wordpress theme functions.php to removed the last empty line.
