### ISSUE TITLE
With Latest Build 0.65  Numerous issues with  redstone.xmlrpc and beans BeanInfo,Introspector, PropertyDescriptor

### ISSUE THREAD

**Issue by raghu-softscripts** [canbican/wordpress-java#70]
Hi can
Here with latest version with Android studio and  gradle  build there are somany issues with 
dependencies even we added the maven repository and tried different ways, 
like take code from your repository and integrate directly in local installation here is  our  log message
can you please help us 

W/dalvikvm: Exception Ljava/util/MissingResourceException; thrown while initializing Lcom/softscripts/wptest/wordpress/redstone/xmlrpc/XmlRpcMessages_en_GB;
W/dalvikvm: Exception Ljava/util/MissingResourceException; thrown while initializing Lcom/softscripts/wptest/wordpress/redstone/xmlrpc/XmlRpcMessages;
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41dd3cf8)
W/dalvikvm: threadid=1: uncaught exception occurred
W/System.err: java.lang.ExceptionInInitializerError
W/System.err:     at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.openConnection(XmlRpcClient.java:510)
W/System.err:     at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.beginCall(XmlRpcClient.java:318)
W/System.err:     at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:191)
W/System.err:     at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcProxy.invoke(XmlRpcProxy.java:198)
W/System.err:     at com.softscripts.wptest.wordpress.$Proxy0.getAuthors(Native Method)
W/System.err:     at com.softscripts.wptest.wordpress.Wordpress.getAuthors(Wordpress.java:414)
W/System.err:     at com.softscripts.wptest.LoginActivity.onCreate(LoginActivity.java:72)
W/System.err:     at android.app.Activity.performCreate(Activity.java:5264)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:193)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5299)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: Caused by: java.util.MissingResourceException: Can't find resource for bundle 'com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcMessages_en_GB', key ''
W/System.err:     at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
W/System.err:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
W/System.err:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
W/System.err:     at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcMessages.<clinit>(XmlRpcMessages.java:67)
W/System.err: 	... 21 more
W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.softscripts.wptest, PID: 19194
                  java.lang.ExceptionInInitializerError
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.openConnection(XmlRpcClient.java:510)
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.beginCall(XmlRpcClient.java:318)
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:191)
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcProxy.invoke(XmlRpcProxy.java:198)
                      at com.softscripts.wptest.wordpress.$Proxy0.getAuthors(Native Method)
                      at com.softscripts.wptest.wordpress.Wordpress.getAuthors(Wordpress.java:414)
                      at com.softscripts.wptest.LoginActivity.onCreate(LoginActivity.java:72)
                      at android.app.Activity.performCreate(Activity.java:5264)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5299)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.util.MissingResourceException: Can't find resource for bundle 'com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcMessages_en_GB', key ''
                      at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcMessages.<clinit>(XmlRpcMessages.java:67)
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.openConnection(XmlRpcClient.java:510) 
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.beginCall(XmlRpcClient.java:318) 
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:191) 
                      at com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcProxy.invoke(XmlRpcProxy.java:198) 
                      at com.softscripts.wptest.wordpress.$Proxy0.getAuthors(Native Method) 
                      at com.softscripts.wptest.wordpress.Wordpress.getAuthors(Wordpress.java:414) 
                      at com.softscripts.wptest.LoginActivity.onCreate(LoginActivity.java:72) 
                      at android.app.Activity.performCreate(Activity.java:5264) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:5299) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647) 
                      at dalvik.system.NativeStart.main(Native Method) 
Application terminated.

**Comment by canbican** [comment]
Thanks for the error log. I am not sufficiently familiar with building this library with Android. It seems that the actual cause of the error is:

``W/System.err: Caused by: java.util.MissingResourceException: Can't find resource for bundle 'com.softscripts.wptest.wordpress.redstone.xmlrpc.XmlRpcMessages_en_GB', key ''``

I don't think it has much to do with this library.

P.S. : Because of the xmlrpc library dependency, it's not a good idea to use wordpress-java in an Android project. Check licenses when incorporating libraries if you want to publish them in Google Play.

**Comment by raghu-softscripts** [comment]
Hi Can 

Can i help you to fix this on android studio  have throughed some part  from your code base

**Comment by canbican** [comment]
Sure, feel free to submit a pull request.
